### ISSUE TITLE
Runaway process when used on large files

### ISSUE THREAD

**Issue by acb** [ly95/vsc.php-symbols#10]
VSCode version: 1.8.1
Operating system: Ubuntu 14.04

As of this latest vscode version when I execute `workbench.action.gotoSymbol` on a large php file (1500+ lines) the symbols never appear and just have the loading bar go forever.

Additionally, when I close vscode there's still a code process that won't die unless I `sudo kill` it.  That process also goes crazy on CPU, sitting at 100% CPU according to `top` until I kill it.  If I don't kill the rogue process and restart vscode and try to use `workbench.action.gotoSymbol` on another large php file it will create another out of control process at 100% CPU and so on.

I unfortunately can't provide you with the files that are triggering this behavior since they're part of my company's source code.  Since it happens on any of our large php files though I believe all you should need to reproduce is a 1,500 line or so php file with lots of functions declared.

**Comment by heisjj** [comment]
I'm running into this same issue, @acb. And I know another developer who is too, so it's fairly safe to assume it isn't specific to your files.

**Comment by acb** [comment]
@heisjj well it's good to know that it's not something weird with me!  Do you happen to have a file on hand you could put in pastebin and link here? I figure it'll be easier for @ly95 to debug if we can just present a file that reproduces the issue.

**Comment by heisjj** [comment]
Sorry, @acb my situation is similar to yours. I can't post any files because it'd put my company's website at risk.


________________________________

**Comment by ly95** [comment]
@acb @heisjj I will make some tests on ubuntu14. Thanks for report.

**Comment by acb** [comment]
@ly95 I just tested on another machine and found some information that might be helpful.  I believe this old machine was on version 2.0.0 of your extension and it worked just fine, but updating to version 2.0.3 (the latest version) causes the bug to reappear.

This new machine is also running vscode 1.8.1 but is on Ubuntu 16.04, so it happens on both versions of Ubuntu.

As a workaround for now, is there a way we could manually download and install version 2.0.0? Thanks for your help!

**Comment by ly95** [comment]
@acb @heisjj Hi all. Please upgrade the new version v2.1.0 , It can be work fine.

**Comment by heisjj** [comment]
@ly95 Thank you for creating and maintaining this plugin!

On Jan 21, 2017, at 7:48 PM, Yang Lin <notifications@github.com<mailto:notifications@github.com>> wrote:


@acb<https://github.com/acb> @heisjj<https://github.com/heisjj> Hi all. Please upgrade the new version v2.1.0 , It can be work fine.

-

**Comment by acb** [comment]
I just updated and it's working again! @ly95 thanks for your help!
