### ISSUE TITLE
刚升级到最新的 2.0.4 打开 outline 还是有问题

### ISSUE THREAD

**Issue by hdwong** [ly95/vsc.php-symbols#11]
使用 Mac OS X，估计跟机器或者 VSCode 版本无关，因为之前在 2.0 前的版本都能用，升级了之后就出问题了。

我的 php 文件不大（500行内），但是继承了一个父类，而这个类是在一个 PHP C 扩展里面实现，类似鸟哥的 yaf 框架，我用快捷键 [cmd]+[shift]+[o] 打开 outline 的时候，进度条一直在滚动，打开终端看，一个 "Code Helper" 的进程消耗了一个核 100% 资源。

希望能帮助到你解决问题，期待下个版本修复，谢谢。

**Comment by ly95** [comment]
你好，问题以及修复，请更新安装2.1.0版本

**Comment by hdwong** [comment]
已经可用，多谢你。
