### ISSUE TITLE
Go to Symbol on project

### ISSUE THREAD

**Issue by ChechoPerezH** [ly95/vsc.php-symbols#2]
the navigation of Symbols only works on the file open, can i find a Symbol on all project? (like sublimetxt :tongue: )

**Comment by ly95** [comment]
good idea, I have no plan on it. maybe support in the future.

**Comment by ChechoPerezH** [comment]
Ok! thnx, i hope it comes soon...  i'll wait for it!!! :smile:

**Comment by ly95** [comment]
Thank you. 😊

**Comment by arturolinares** [comment]
Was this implemented?
