### ISSUE TITLE
无法使用这个插件

### ISSUE THREAD

**Issue by Simluzifer** [ly95/vsc.php-symbols#3]
当我按下crtl+shift+o时，它没有弹出php的符号来，只显示一个蓝色的滚动条滚动。
然后用开发这工具查看，他报了三个错：

> threadService.ts:207  [Extension Host] Uncaught Exception:  Error: ENOENT: no such file or directory, open 'D:\e:\file\to\path\DictController.class.php'
> threadService.ts:207 [Extension Host] Error: ENOENT: no such file or directory, open 'D:\e:\file\to\path\DictController.class.php'
> shell.ts:400 ENOENT: no such file or directory, open 'D:\e:\file\to\path\DictController.class.php': Error: ENOENT: no such file or directory, open 'D:\e:\file\to\path\DictController.class.php'

你可以看到是文件路径出错了，我的文件实际在e盘，但是路径前面多了一个‘D:\’

**Comment by ly95** [comment]
感谢反馈，内容很详细，我会尽快处理。

**Comment by Simluzifer** [comment]
我已更新了此插件，已经可以正常使用了，谢谢作者！

**Comment by ly95** [comment]
已经发布新版本 0.1.2。win10下已经测试通过

![pic](https://cloud.githubusercontent.com/assets/1676886/15748552/ef6de64e-2911-11e6-8116-bc0ddc643b1c.jpg)
