### ISSUE TITLE
Invalid symbol being displayed

### ISSUE THREAD

**Issue by riula** [ly95/vsc.php-symbols#5]
First thanks for all your hard work. 

The issue I'm having is methods are showing up in the symbol list that shouldn't be. I suspect this is because it's including the comments as well. 

Example: `/** Override function to add something */`

"to" will appear in the symbol list as a method

**Comment by ly95** [comment]
thx feedback. I will fix it, ASAP.

**Comment by riula** [comment]
Hey, any chance I can get an update on this? Thank you!

**Comment by theikalman** [comment]
This also happen to me. And here is the symbols that included from comment:
![screenshot from 2016-08-19 11-37-44](https://cloud.githubusercontent.com/assets/7039123/17799041/69b1a6b2-6601-11e6-893d-75215cfaf6b3.png)

**Comment by ly95** [comment]
Fixed. The new version (v2.0.0) has been released.

**Comment by jens1o** [comment]
Thanks!
