### ISSUE TITLE
v2.0.3 not working at all

### ISSUE THREAD

**Issue by bingzheyuan** [ly95/vsc.php-symbols#7]
I tried with a simple file and the plugin is not working anymore. There is no result coming out.
```php
<?php 
use Think\Model;
class CacheModel extends Model {

    public function cache($key,$value = '',$life = 3600){
        // logic code
    }

}
?>
```

**Comment by bingzheyuan** [comment]
I guess something wrong with my vscode, should not be the problem of this extension.

**Comment by ly95** [comment]
😊 please let me know if the issue is solved.

**Comment by bingzheyuan** [comment]
I am afraid it's not. I test it today and the extension still gives no result. Moreover, when I use the extension,  it disables all IntelliSense in vscode.

**Comment by ly95** [comment]
Notes:

1. check the version
2. select language mode "php" & save file.

![pic](https://cloud.githubusercontent.com/assets/1676886/21674959/fdf1edb0-d36a-11e6-9d03-5c88d638b1b9.jpg)

**Comment by bingzheyuan** [comment]
well, today everything seems to be fine again, I have done no modification, odd. Please close the issue since I can't really describe the problem.

**Comment by ly95** [comment]
thanks for reply.
