### ISSUE TITLE
在大文件中无法使用并且导致CPU暴增

### ISSUE THREAD

**Issue by hnlxl** [ly95/vsc.php-symbols#9]
# 环境
windows10
# 使用问题
300行的可以使用，3000行的查找不出来。并且一旦在3000行的文件中查找符号，其他所有文件也不能查找了。
# CPU表现
- 3000行的文件中开始查找后，有一个Code.exe进程CPU占用率稳定在50%。
- 关闭VS Code主窗口后该进程不会结束，再启动VS Code主窗口并在此查找符号后，又一个Code.exe进程CPU占用率上升到40%以上，此时总CPU占用率超过90%。
- 如果在VS Code运行期间强制关闭CPU占用率暴增的进程，VS Code主窗口回报错：“扩展主机意外终止。请重新加载窗口以恢复。”
# 辅助说明
升级2.0版本后才发现有该问题，但不确定2.0版本之前是否有该问题。
**我那个3000行的文件除了文件大之外，里面还是用了闭包函数，而且是一个不太规范的代码。所以问题可能不是因为文件行数造成的，有可能是闭包函数、函数中定义函数造成的。**

**Comment by ly95** [comment]
收到，谢谢反馈，后续会解决此问题。

**Comment by ly95** [comment]
Please upgrade the new version v2.1.0 , It can be work fine.
